# Generated by Django 6.0 on 2026-04-25

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0054_bookmarkbundle_filter_shared_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="enable_tag_recommendation",
            field=models.BooleanField(default=True, null=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tag_recommendation_count",
            field=models.IntegerField(default=5, null=False, validators=[MinValueValidator(1)]),
        ),
    ]
